#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

apt:
  sources_list: | 
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-backports main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse

packages:
 - apache2-utils
 - apt-transport-https
 - ca-certificates
 - curl
 - gnupg-agent
 - software-properties-common

write_files:
 - path: /etc/environment
   permissions: 0644
   content: | 
     KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
   append: true
 - path: /etc/rancher/k3s/registries.yaml
   permissions: 0644
   content: | 
     mirrors:
       "registry.local:5000":
         endpoint:
          - http://registry.local:5000
   append: false

runcmd:
 - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -'
 - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
 - apt-get update -y
 - apt-get install -y docker-ce docker-ce-cli containerd.io -y
 - 'curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --docker" sh -s -'
 - chmod 644 /etc/rancher/k3s/k3s.yaml
 - 'docker volume create local_registry'
 - 'docker container run -d --name registry.local -v local_registry:/var/lib/registry --restart always -p 5000:5000 registry:2'
 - 'echo "127.0.0.1 registry.local" >> /etc/hosts'
 - 'git clone https://github.com/signalfx/app-dev-workshop.git /home/ubuntu/workshop'
 - chown -R ubuntu:ubuntu /home/ubuntu/workshop 
 - 'curl https://raw.githubusercontent.com/signalfx/app-dev-workshop/master/etc/motd -o /etc/motd'
 - 'curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash'
 - 'curl -OL https://github.com/derailed/k9s/releases/download/v0.17.7/k9s_Linux_x86_64.tar.gz'
 - tar xvfz k9s_Linux_x86_64.tar.gz 
 - mv k9s /usr/local/bin
